# prometheus.yml
global:
  scrape_interval: 1s
  external_labels:
      monitor: 'my-monitor'
scrape_configs:
  - job_name: 'sws-spectest'
    scrape_interval: '1s'
    metrics_path: '/swagger-stats/metrics'
    target_groups:
      - targets: ['141.40.254.131:10010']
  - job_name: 'prometheus'
    target_groups:
        - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    target_groups:
        - targets: ['node-exporter:9100']
  - job_name: 'c-advisor'
    target_groups:
        - targets: ['localhost:8080']
rule_files:
  - 'alert.rules'
